In [ ]:
import numpy as np 
import pandas as pd

**Creating a DataFrame**

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [11]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [13]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new column**

In [18]:
df2["Designation"] = ["HR","ENG","DR","INTERN"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         ENG
2  Peter   29    Berlin   62000          DR
3  Linda   42    London   85000      INTERN

**Removing Columns**

In [19]:
df2.drop(0,axis=0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000         ENG
2  Peter   29  Berlin   62000          DR
3  Linda   42  London   85000      INTERN

In [20]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         ENG
2  Peter   29    Berlin   62000          DR
3  Linda   42    London   85000      INTERN

**Selecting Rows**

In [23]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         ENG
2  Peter   29    Berlin   62000          DR
3  Linda   42    London   85000      INTERN

In [21]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000          HR
1  Anna   34     Paris   70000         ENG

In [22]:
df2.iloc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation    INTERN
Name: 3, dtype: object

**Selecting Subsets of Rows and Columns**

In [25]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [27]:
df2.loc[[1,2]][["Age","City"]]

   Age    City
1   34   Paris
2   29  Berlin

**Conditional Selection**

In [28]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         ENG
2  Peter   29    Berlin   62000          DR
3  Linda   42    London   85000      INTERN

In [29]:
#I only want to see those people whose age is above 30

In [30]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000         ENG
3  Linda   42  London   85000      INTERN

In [ ]:
#I only want poeple whose age is above 30 and their city must be paris

In [32]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000         ENG